### ISSUE TITLE
Disable signature verification be default

### ISSUE THREAD

**Issue by xhliu** [BOXFoundation/erc20-rest-service#9]
Otherwise, 

> "2018-04-26 15:24:50.490  INFO 5660 --- [nio-8080-exec-3] fm.castbox.wallet.util.APISignUtils      : toSignStr is amount=1&timeStamp=0&toAddress=0xce1f13502de520f649b3c6655a0452d8a355d55f&tokenSymbol=ETH
> 2018-04-26 15:31:08.989  INFO 5660 --- [nio-8080-exec-5] fm.castbox.wallet.util.APISignUtils      : Verify Sign Fail:
> 
> java.lang.RuntimeException: java.io.IOException: DER length more than 4 bytes: 90
>         at fm.castbox.wallet.util.algorithm.ECDSAAlgorithm$ECDSASignature.decodeFromDER(ECDSAAlgorithm.java:267) ~[main/:na]
>         at fm.castbox.wallet.util.algorithm.ECDSAAlgorithm.verify(ECDSAAlgorithm.java:152) ~[main/:na]
>         at fm.castbox.wallet.util.APISignUtils.verifySign(APISignUtils.java:94) [main/:na]
>         at fm.castbox.wallet.util.APISignUtils.verifySign(APISignUtils.java:79) [main/:na]"

**Comment by freedomhero** [comment]
already added config property to switch off signature validation, also removed the disturbing log.
https://github.com/BOXFoundation/erc20-rest-service/commit/80211c02415f1c6777000331c9ae9060db4c0c96
